version: '3.6'

services:
  web:
    environment:
      # More environment variables may be available.
      # @see https://ddev.readthedocs.io/en/stable/users/extend/custom-commands/#environment-variables-provided
      - DRUSH_OPTIONS_URI=https://${DDEV_SITENAME}.ddev.site

      - PHP_IDE_CONFIG=serverName=${DDEV_SITENAME}.ddev.site
